### ISSUE TITLE
what is the role of damp

### ISSUE THREAD

**Issue by Usaywook** [AlgTUDelft/WCSAC#2]
according to [this code](https://github.com/AlgTUDelft/WCSAC/blob/6536929bb3a167090752305373bf16e726994305/wc_sac/sac/wcsac.py#L438-L442) the damping term is added for pi_loss.
The formula did not include this part, what does it mean?

**Comment by sijiyanci** [comment]
Can I ask you if running wcsac is effective? Will the return be low? I ran the wcsac algorithm in the environment pointgoal1, but the result was not ideal. Although the cost constraint was met, the return was particularly low.

**Comment by sijiyanci** [comment]
@Usaywook I tried to run sac Py, its beta tends to zero prematurely, resulting in high cost. Wcsac is similar to sac. The performance after removing damp is very similar to sac. I think the function of damp is to make up for the problem that beta tends to zero prematurely. Otherwise, the constraints after beta tends to zero will hardly work.

**Comment by qisong-yang** [comment]
Hi @Usaywook @sijiyanci, Thanks for your questions! To make the algorithm tunable for the more complex environments, we added `damp`. It is actually the MDMM method. For the constrained optimization, you can have a look: https://authors.library.caltech.edu/26703/2/postscript.pdf  (and used e.g. here: https://proceedings.neurips.cc/paper/2021/file/79ec2a4246feb2126ecf43c4a4418002-Paper.pdf  Same as in this blog post: https://www.engraved.blog/how-we-can-make-machine-learning-algorithms-tunable/

**Comment by Usaywook** [comment]
@qisong-yang Thank you for sharing great references. I experimented with the damping term removed. When the cost limit is high, beta tends to converge to 0 immediately after learning starts. When the cost limit is low, the beta value tends to rise and then fall to converge to 0. When the beta value is 0, it becomes the same objective function as SAC, meaning that the interaction with the cost is no longer needed. I think the damping term is a device to make the interaction with cost longer. Am I right? @qisong-yang @sijiyanci

**Comment by qisong-yang** [comment]
Hi @Usaywook, I basically agree with you. We usually set a learning rate (a small value) for beta, but when we are not safe, beta cannot instantly go to a value corresponding to the safety. After we are safe, we also cannot quickly pull it back. So, to better reflect the safety, we have this term.
