### ISSUE TITLE
What was the damping scale used in your experiments?

### ISSUE THREAD

**Issue by acl21** [AlgTUDelft/WCSAC#4]
Dear authors, what was the damping scale used for experiments reported in the paper? 

Any information on this will save us a lot of computing. 😅

**Comment by qisong-yang** [comment]
Dear @acl21, Thanks for your question! To make the algorithm tunable for the more complex environments, we added damp. It is actually the MDMM method. For the constrained optimization, you can have a look: https://authors.library.caltech.edu/26703/2/postscript.pdf (and used e.g. here: https://proceedings.neurips.cc/paper/2021/file/79ec2a4246feb2126ecf43c4a4418002-Paper.pdf Same as in this blog post: https://www.engraved.blog/how-we-can-make-machine-learning-algorithms-tunable/

**Comment by acl21** [comment]
Thank you for your response. I understood the motivation for damp. The two-part blog posts you shared were very helpful. However, my question is about the `damp_scale` value you used in your experiments. From the looks of it in `sac/wcsac.py`, it appears you set it to 0. Is that right?

**Comment by qisong-yang** [comment]
Indeed, for the StaticEnv, you should use damp_s 0.0 and lr_s 1.0. For the more complex ones, you may use the default values there.

**Comment by acl21** [comment]
This answers my question. Once again, thank you for your reply. :)
